# Generated by Django 3.2.5 on 2021-07-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Nome')),
                ('lastname', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('admission_date', models.DateField(verbose_name='Data de Admissão')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'unique_together': {('firstname', 'lastname', 'admission_date')},
            },
        ),
    ]
