# Generated by Django 3.2.5 on 2021-07-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Nome')),
                ('lastname', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('admission_date', models.DateField(verbose_name='Data de Admissão')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'unique_together': {('firstname', 'lastname', 'admission_date')},
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Posto de Trabalho',
                'verbose_name_plural': 'Postos de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='País')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('district', models.CharField(max_length=255, verbose_name='Bairro')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=255, verbose_name='Número')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escala.place')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.doctor', verbose_name='Médico')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.place', verbose_name='Local de Trabalho')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'unique_together': {('date', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='DayOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(2, 'Segunda'), (3, 'Terça'), (4, 'Quarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Sábado'), (1, 'Domingo')], verbose_name='Folga')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.doctor', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Folga',
                'verbose_name_plural': 'Folgas',
                'unique_together': {('day', 'doctor')},
            },
        ),
    ]
