# Generated by Django 3.2.5 on 2021-07-13 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Posto de Trabalho', 'verbose_name_plural': 'Postos de Trabalho'},
        ),
        migrations.CreateModel(
            name='DayOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(2, 'Segunda'), (3, 'Terça'), (4, 'Quarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Sábado'), (1, 'Domingo')], verbose_name='Folga')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.doctor', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Folga',
                'verbose_name_plural': 'Folgas',
            },
        ),
    ]
