# Generated by Django 3.2.5 on 2021-07-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_auto_20210713_0131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayof',
            unique_together={('day', 'doctor')},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.doctor', verbose_name='Médico')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.place', verbose_name='Local de Trabalho')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'unique_together': {('date', 'doctor')},
            },
        ),
    ]
